### Import the dataset

#### Objective
- To inspect, clean, and prepare the synthetic health dataset for econometric and machine learning analysis, ensuring internal consistency and analytical validity.

#### Notes
- The dataset is synthetic and used for methodological demonstration. Cleaning steps follow best practices in applied health economics.

In [1]:
import pandas as pd

# Define file path clearly
file_path = "Health_data.csv"

# Load dataset into a DataFrame
df = pd.read_csv(file_path)

# Preview the first five rows
print(df.head())

            Name  Age  Gender Blood Type Medical Condition Date of Admission  \
0  Bobby JacksOn   30    Male         B-            Cancer        31-01-2024
1   LesLie TErRy   62    Male         A+           Obesity        20-08-2019
2    DaNnY sMitH   76  Female         A-           Obesity        22-09-2022
3   andrEw waTtS   28  Female         O+          Diabetes        18-11-2020
4  adrIENNE bEll   43  Female        AB+            Cancer        19-09-2022

             Doctor                    Hospital Insurance Provider  \
0     Matthew Smith             Sons and Miller         Blue Cross
1   Samantha Davies                     Kim Inc           Medicare
2  Tiffany Mitchell                    Cook PLC              Aetna
3       Kevin Wells  Hernandez Rogers and Vang,           Medicare
4    Kathleen Hanna                 White-White              Aetna

   Billing Amount  Room Number Admission Type Discharge Date   Medication  \
0     18856.28131          328         Urgent     02-02-2024  Paracetamol
1     33643.32729          265      Emergency     26-08-2019    Ibuprofen
2     27955.09608          205      Emergency     07-10-2022      Aspirin
3     37909.78241          450       Elective     18-12-2020    Ibuprofen
4     14238.31781          458         Urgent     09-10-2022   Penicillin

   Test Results
0        Normal
1  Inconclusive
2        Normal
3      Abnormal
4      Abnormal

#### Inspect the data

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

#### Data inspection and cleaning

In [3]:
df.shape

(55500, 15)

In [4]:
#column names
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

#### Remove the incosistencies if any

In [5]:
# Clean and standardize column names
df.columns = (
    df.columns
      .str.strip()                # remove leading/trailing spaces
      .str.lower()                # convert to lowercase
      .str.replace(r"\s+", "_", regex=True)  # replace spaces with underscores
)

In [6]:
# Inspect the data types
df.dtypes

name                   object
age                     int64
gender                 object
blood_type             object
medical_condition      object
date_of_admission      object
doctor                 object
hospital               object
insurance_provider     object
billing_amount        float64
room_number             int64
admission_type         object
discharge_date         object
medication             object
test_results           object
dtype: object

#### Check the missing values

In [8]:
df.isna().sum()
print(df.isna().mean().sort_values(ascending=False))

name                  0.0
age                   0.0
gender                0.0
blood_type            0.0
medical_condition     0.0
date_of_admission     0.0
doctor                0.0
hospital              0.0
insurance_provider    0.0
billing_amount        0.0
room_number           0.0
admission_type        0.0
discharge_date        0.0
medication            0.0
test_results          0.0
dtype: float64

#### Check for the duplicates

In [9]:
df.duplicated().sum()

534

#### Remove any duplicates

In [10]:
df[df.duplicated()]

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
50023,Samuel joYCe,56,Male,O+,Arthritis,03-11-2022,Krista Hartman,Thomas-Ballard,UnitedHealthcare,15654.830590,157,Urgent,22-11-2022,Aspirin,Inconclusive
50040,KIMBErly vasqueZ,26,Male,A-,Obesity,23-10-2023,Jennifer Bennett,Cowan Inc,UnitedHealthcare,38142.109680,313,Urgent,18-11-2023,Penicillin,Abnormal
50055,SCoTT tHOrNton,55,Female,B-,Obesity,08-04-2021,Joshua Ingram,Keller LLC,Medicare,30894.904510,455,Urgent,15-04-2021,Aspirin,Abnormal
50070,wiLliam LEe,27,Female,O+,Arthritis,31-01-2020,Lauren Montgomery,Winters-Simon,Cigna,46229.434900,153,Elective,13-02-2020,Lipitor,Normal
50078,chRistOPheR NoRrIs,38,Male,AB-,Arthritis,14-01-2023,Denise Blair,Inc Morales,Medicare,9072.127142,452,Emergency,12-02-2023,Penicillin,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55461,connOR coMPTon,63,Male,A+,Asthma,21-08-2021,Jonathan Allen,"and Willis Mullins, Bowers",Medicare,1936.702824,375,Emergency,16-09-2021,Paracetamol,Normal
55462,alYSsA mIlLER,35,Female,A-,Diabetes,30-06-2022,Ryan Price,Shelton-Gallagher,UnitedHealthcare,2210.460898,289,Elective,27-07-2022,Penicillin,Normal
55464,ChRIs huGHeS,35,Female,AB-,Obesity,28-02-2024,Katelyn Perry,Lyons-Hansen,Blue Cross,11889.154510,128,Emergency,14-03-2024,Paracetamol,Abnormal
55484,keNNEtH alvarez,80,Male,O+,Cancer,05-05-2022,Andrew Conner,Sons Mayo and,Cigna,45653.802310,114,Elective,17-05-2022,Aspirin,Normal
55491,lInDA grIFfin,47,Female,O+,Obesity,21-06-2020,Danielle Davis,"and King Jordan Johnson,",Aetna,15715.551080,310,Emergency,25-06-2020,Lipitor,Abnormal

#### check for the values

In [14]:
# Generate descriptive statistics for selected columns
df[['age', 'billing_amount']].describe().transpose()

,count,mean,std,min,25%,50%,75%,max
age,55500.0,51.539459,19.602454,13.00000,35.000000,52.00000,68.000000,89.00000
billing_amount,55500.0,25539.316097,14211.454431,-2008.49214,13241.224655,25538.06938,37820.508432,52764.27674

#### Frequency distriction for the categories

In [15]:
# Frequency counts for key categorical variables (including NaN values)
categorical_columns = [
    "gender",
    "insurance_provider",
    "admission_type",
    "medical_condition"
]

for col in categorical_columns:
    print(f"\nValue counts for '{col}':")
    print(df[col].value_counts(dropna=False))

Value counts for 'gender':
gender
Male      27774
Female    27726
Name: count, dtype: int64

Value counts for 'insurance_provider':
insurance_provider
Cigna               11249
Medicare            11154
UnitedHealthcare    11125
Blue Cross          11059
Aetna               10913
Name: count, dtype: int64

Value counts for 'admission_type':
admission_type
Elective     18655
Urgent       18576
Emergency    18269
Name: count, dtype: int64

Value counts for 'medical_condition':
medical_condition
Arthritis       9308
Diabetes        9304
Hypertension    9245
Obesity         9231
Cancer          9227
Asthma          9185
Name: count, dtype: int64

#### consistency checks

In [16]:
# Age vs admission
df.loc[df['age'] < 0]

Empty DataFrame
Columns: [name, age, gender, blood_type, medical_condition, date_of_admission, doctor, hospital, insurance_provider, billing_amount, room_number, admission_type, discharge_date, medication, test_results]
Index: []

In [17]:
#cost vs admisssion type
df.groupby('admission_type')['billing_amount'].describe()

,count,mean,std,min,25%,50%,75%,max
admission_type,,,,,,,,
Elective,18655.0,25602.226311,14228.275326,-1660.009373,13285.37757,25656.932460,37840.97811,52764.27674
Emergency,18269.0,25497.397157,14163.005577,-1316.618581,13265.69184,25379.570920,37689.48471,52271.66375
Urgent,18576.0,25517.364497,14242.632174,-2008.492140,13192.68485,25550.368225,37910.31310,52373.03237

In [20]:
# Save cleaned DataFrame to CSV
# Save cleaned DataFrame to CSV in the current folder
df.to_csv("health_data_cleaned.csv", index=False)

## Data Cleaning Summary

- The dataset contains 55500 observations and 15 variables.
- Column names were standardised for reproducibility.
-  duplicate observations were identified and handled.
- Missing values were audited and assumed to be random for demonstration purposes.
- Implausible values (if any) were addressed.
- The cleaned dataset is suitable for econometric and machine learning analysis.